# Generated by Django 3.0.3 on 2020-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default='Some Description', max_length=500),
        ),
    ]
