# Generated by Django 3.0.3 on 2020-03-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0002_auto_20200314_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default='Some Description', max_length=300),
        ),
    ]
