# Generated by Django 3.0.3 on 2020-03-26 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0004_auto_20200323_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='xyz123@gmail.com', max_length=100)),
                ('password', models.CharField(default='123456', max_length=50)),
                ('mobileNumber', models.IntegerField(default='1234567890')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
