# Generated by Django 3.0.3 on 2020-03-26 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0005_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobileNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
