# Generated by Django 3.0.3 on 2020-03-26 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0006_auto_20200326_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(default='xyz123@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobileNumber',
            field=models.IntegerField(default='1234567890'),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='123456', max_length=50),
        ),
    ]
