# Generated by Django 3.0.3 on 2020-03-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0010_auto_20200330_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
