# Generated by Django 3.0.3 on 2020-03-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0012_auto_20200330_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='customId',
            field=models.IntegerField(default=1),
        ),
    ]
