# Generated by Django 3.0.3 on 2020-03-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0013_image_customid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='customId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
