# Generated by Django 3.0.3 on 2020-05-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0015_auto_20200509_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
