# Generated by Django 3.0.3 on 2020-05-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0016_employee_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
