# Generated by Django 3.0.3 on 2020-05-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0017_auto_20200510_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
