# Generated by Django 3.0.3 on 2020-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0020_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
